### ISSUE TITLE
USER STORY: Initial Django Setup

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#1]
As a developer I can setup a new Django project so that I can create the project's structure

**Tasks**

- [x] Initialise a new Django Project
- [x] Create new project with the name Coolcoders
- [x] Create the first app  named blog and add it to settings.py
- [x] Create env.py file to hide the secret keys
- [x] Add env.py to .gitignore so that the secret keys stay private
- [x] Create a new virtual environment to install packages

**Comment by DarrachBarneveld** [comment]
Set up initial project/app and config files
