### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#10]
As a **User**, I can log out so that I can secure my account from potential hacks

**Acceptance Criteria:**
1. Users can successfully log out of their accounts.
2. Clear feedback is provided to users upon successful log-out.
3. Redirect users to the home page or a designated landing page after logging out.

**Tasks**
- [x] Add a logout button to the navigation bar when a user is logged in
- [x] Have the logout button redirect to a confirmation page
- [x] Logout user and redirect to home page on confirmation
- [x] Notify user on a successful logout

**Comment by DarrachBarneveld** [comment]
Users can confirm log out and are notified of the result
