### ISSUE TITLE
USER STORY: Profile Page Edit

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#11]
As a **User**, I can view my profile page so that I can update my information

**Acceptance Criteria:**
1. Authenticated users can access their profile page
2. Authenticated users can edit there personal information
3. Authenticated users can update their passwords

**Tasks**
- [x] Create a user-friendly profile page template, including the display of personal information.
- [x] Create an authenticated settings button on the profile template
- [x] Create an edit profile template
- [x] Create a form to update users personal information
- [x] Create a form to update users password information
- [x] Create a form to update users bio information
- [x] Render any error messages back to the user

**Comment by DarrachBarneveld** [comment]
Completed Profile edit page with 3 individual forms to update user information, biography and password. Error handling and crud notifications in place for UX purposes.
