### ISSUE TITLE
USER STORY: Article Creation

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#12]
As a **User**, I can post an article so that I can share my insights with the community.

**Acceptance Criteria:**
1. Authenticated users can create and post articles through an add post button.
2. A user-friendly form where users can upload content is rendered
3. Appropriate error handling is in place for any issues during article creation and editing.
4. Articles are saved to a database
5. Users should receive a confirmation message upon successful article editing.

**Tasks**
- [x] Create an Article Model with all necessary fields
- [x] Create a add post button on the navbar for authenticated users
- [x] Develop a user-friendly article creation form that allows users to input article content.
- [x] Create a template for rendering the article form
- [x] Implement authentication to ensure only logged-in users can post articles
- [x] Implement user notifications for successful article creation and updates.
- [x] Articles are saved to a database for future use.
- [x] Create error handling mechanisms to provide clear feedback in case of issues during article creation
- [x] Add a notification upon article creation

**Comment by DarrachBarneveld** [comment]
Add Post Page view class created which links to a add post page. Inclusion of Crispy Forms and a Summernote widget allow the user to create new posts. All crud operations are sent to the user upon the result. Only authenticated users can post articles and all fields must be completed with correct error handling and UI feedback incorporated
