### ISSUE TITLE
USER STORY: Edit / Delete Article

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#13]
As a User, I can edit my articles as the author, so that I can keep my content up to date.

**Acceptance Criteria:**
1. Authenticated users who are the authors of articles can access an "Edit" button for their articles.
2. A user-friendly editing form should be provided, allowing users to modify the article's content, including title, body text, and images.
3. The form should perform data validation to ensure required fields are filled and data is correctly formatted.
4. Clear error messages should be provided for any validation or submission issues.
5. The form should perform data validation to ensure required fields are filled and data is correctly formatted.
6. Users should receive a confirmation message upon successful article editing.
7. A user should have the ability to delete an article from the edit article form

**Tasks**
- [x] Create an "Edit" button that is accessible to the authenticated authors of articles.
- [x] Set up a template for rendering the article editing form
- [x] Render the article form with current data allowing authors to make modifications to the article's content.
- [x] Securely update the article in the database with the edited content.
- [x] Add a delete button with a confirmation of delete modal
- [x] Provide clear feedback in case of errors during article editing
- [x] Add notifications to confirm successful article editing

**Comment by DarrachBarneveld** [comment]
EditPostPage view created, html template and urls linked. CRUD notifications sent to user upon outcome of operation. Error feedback provided to user. All edits are sent to database for admin reviewal.
