### ISSUE TITLE
USER STORY: Comment Creation

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#14]
As a User, I can create comments on articles, so that I can engage with the content and share my thoughts.

**Acceptance Criteria:**
1. Authenticated users can access a comment form section on articles.
2. A user-friendly comment creation form is provided, allowing users to input their comments.
3. User-submitted comments should be securely stored and associated with the respective articles and user accounts.
4. Clear error messages should be displayed for any validation or submission issues.
5. Users should receive a confirmation message upon successful comment creation.

**Tasks**
- [x] Create a Comment Model class with relations to user and post models
- [x] Create a "Comment" form section that is accessible to authenticated users on articles.  
- [x] Implement data validation to ensure comments meet the required criteria. 
- [x] Store user-submitted comments in the database in a relationship to the article.
- [x] Add user notifications to confirm successful comment submission.

**Comment by DarrachBarneveld** [comment]
Comments can be created from a Comment Form class that is rendered to the post detail page. Comments are sent to the database for pending review, and once they are approved will be visible on the post detail page.

Notifications are sent to the user upon completing any crud operations whether successful or not
