### ISSUE TITLE
USER STORY: Comment Delete

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#15]
As a User, I can delete my own comments, so that I can remove unwanted opinions. 

**Acceptance Criteria:**
1. Authenticated users can access a "Delete" option for their own comments.
2. Upon selecting the "Delete" option, a confirmation prompt should be displayed for confirmation
3. Upon confirmation, the comment should be permanently deleted from the database
4. A success message should be displayed to the user upon successful deletion
5. Appropriate error handling should be in place for any issues during the deletion process.

**Tasks**
- [x] Create a "Delete" button that is accessible to authenticated users for their own comments
- [x] Implement a confirmation prompt to confirm the user's intention to delete the comment
- [x] Upon form submission delete the comment from the database
- [x] Create error handling mechanisms to provide clear feedback in case of issues during comment deletion.

**Comment by DarrachBarneveld** [comment]
Users can delete comments by clicking the delete button. This button appears only if the user is the author of the comment. A popup modal comes to allow the user to confirm their actions. Users receive notifications on the outcome of their actions
