### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#16]
As a **User**, I can view content on the home page so that I can stay informed and explore engaging topics.

**Acceptance Criteria:**
1. Display a dedicated section for "Editor's Picks" that showcases selected articles.
2. Features a section for "Trending" articles that highlights current popular topics.
3. A section for "Popular" articles is available on the home page, showcasing articles with the highest engagement.
4. Display a list of categories in navigation tags
5. Render basic information about each rendered article.

**Tasks**
- [x] Create a homepage template and add it into the urls directory
- [x] Create a homepage view
- [x] Filter the database for articles with the most likes to render as trending articles
- [x] Filter the database for articles with the most comments as popular articles
- [x] Select an article for the editors pick
- [x] Render the information from the view to the templates page
- [x] Ensure that the articles listed in each section are linked to the article details page.

**Comment by DarrachBarneveld** [comment]
Home page displays all desired articles with links to each article. Editors pick, trending and popular post are rendered on the home page
