### ISSUE TITLE
USER STORY: Article Detail Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#17]
As a **User**, I can view a selected article with its comments, as well as related articles, so that I can explore in-depth content and engage with the community.

**Acceptance Criteria:**
1. Users can access the article details page by clicking on a listed article
2. The article details page displays the selected article's total content
3. A comments section is present on the article details page, allowing users to view and engage with comments.
4. Users can view related articles or articles from the same category on the article details page.
5. Users can navigate to related articles by clicking on the display card

**Tasks**
- [x] Create a URL pattern and view for the article details page.
- [x] Add an article details template to display rendered content
- [x] Create an Article detail view
- [x] Fetch the relevant article based on the slug
- [x] Fetch related articles based on the article category
- [x] Render the article in a responsive layout with the image at the top followed by the content
- [x] Render the associated article comments below the articles body
- [x] Render the related articles in a sidebar beside the article or below in mobile view
- [x] Ensure navigation is possible by linking the related article cards to detail pages

**Comment by DarrachBarneveld** [comment]
Article detail page created which renders the article and all its associated content. The sidebar contains 3 other articles from the same category. All articles are rendered with: 

1. Authors name as a link to their profile page
2. Title, category, engagement, post date
3. Main article is rendered with full content
