### ISSUE TITLE
USER STORY: Category View

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#18]
As a **User**, I can view articles in a specific category, so that I can explore content that interests me.

**Acceptance Criteria:**
1. Users can select a category to view articles related to their chosen category.
2. The category view page displays article preview cards, each featuring titles, excerpts, and images.
3. Users can click on an article preview card to access the full article details page.
4. Pagination is implemented if there are too many results

**Tasks**
- [x] Create a URL pattern and view for the category view page. 
- [x] Create a category view template to render articles based on the selected category 
- [x] Implement a view for the category page to fetch articles belonging to the chosen category. 
- [x] Design and create article preview cards that display article titles, excerpts, and images.
- [x] Ensure that related articles are fetched based on the category of the selected article.
- [x] Optimise the layout for responsive rendering, including mobile-friendly design.
- [x] Ensure pagination occurs if the return results are too many

**Comment by DarrachBarneveld** [comment]
Implemented a category html template, a CategoryPage ListView for filtering results and added pagination

**Comment by DarrachBarneveld** [comment]
Updated pagination styling with bootstrap
