### ISSUE TITLE
USER STORY: Profile Details Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#19]
As a User, I can view a user's profile page, displaying their posts, favourites and basic information so that I can learn more about the user and their contributions.

**Acceptance Criteria:**
1. Users can access a user's profile page by clicking on a username or profile link.
2. The profile page displays the user's posts.
3. Basic user information, such as name, email, date joined, and bio, is presented.
4. The user profile page layout is responsive, ensuring optimal viewing on various screen sizes.
5. Pagination is implemented for user posts to handle a large number of results effectively.

**Tasks**
- [x] Create a URL pattern for the user profile page. 
- [x] Implement a view for the user profile page, fetching user-specific data.
- [x] Develop a user profile template to display the user's posts, basic information, and favourite articles (if the user is the profile owner).
- [x] Add user analytic metrics such as total posts, comments, likes and favourites
- [x] Ensure that the user profile page layout is responsive and mobile-friendly
- [x] Implement pagination for user posts to manage a large number of results effectively

**Comment by DarrachBarneveld** [comment]
Profile detail page fetches users specific content. Posts, favourites and analytics of a user are rendered to a html template. Pagination occurs for both user posts and favourites if they exceed more that 4 posts. Authenticated profile users can find links to edit their information and posts from this page.
