### ISSUE TITLE
USER STORY: Connect database and Cloudinary storage

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#2]
As a developer I can connect database and media storage so that the user's stored data is stored successfully

**Tasks**
- [x] Configure Django's settings to connect to database.
- [x] Configure settings for ElephantSQL
- [x] Configure settings for static files and media directory roots
- [x] Create superuser for admin panel
- [x] Migrate DB changes

**Comment by DarrachBarneveld** [comment]
Linked Elephants SQL DB and Cloudinary static files storages - Superuser created.
