### ISSUE TITLE
USER STORY: Profile View Favourites

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#20]
As a **User**, I can view my favourites on my profile detail page so that I can reread my favourite articles

**Acceptance Criteria:**
1. The profile detail page includes a section that lists the user's favourite articles.
2. The user's favourites are accessible and viewable only by the authenticated user.
3. All articles are clickable links to the article detail page

**Tasks**
- [x] Create a favourites section on the user's profile detail page.
- [x] In the view fetch all the favourites linked to the users profile
- [x] Configure the rendering of all favourite articles within this section.
- [x] Implement pagination for efficient navigation through a large number of favourite articles.

**Comment by DarrachBarneveld** [comment]
Profile view creates two paginated lists. Favourites are rendered to the profile template. Pagination occurs if there are over 4 results. Users can access the article by clicking the article preview card.
