### ISSUE TITLE
USER STORY: Article Preview Card

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#21]
As a **Developer**, I can created a standardised article preview card for each article, providing key information at a glance so that users can quickly understand the context of an article

**Acceptance Criteria:**

1. Each article on the platform is represented by a standardised article preview card.
2. The article preview card includes essential information, such as the article title, excerpt, author, engagement and publication date.
3. The article preview card features a thumbnail image that provides a visual representation of the article.
4. Users can click on the article preview card to access the full article details page.
5. Users can click on the authors link to access the authors profile page.
6. The layout of the article preview card is responsive and optimised for various screen sizes

**Tasks**
- [x] Create a standardised template for rendering article preview cards. 
- [x] Configure the preview card to include a thumbnail image representing the article
- [x] Ensure that the preview card links to the full article details page for further exploration
- [x] Ensure all views render the necessary analytic information such as likes and comments for each article.
- [x] Design and implement a responsive layout for the article preview card, offering an optimal viewing experience on different devices

**Comment by DarrachBarneveld** [comment]
Article preview cards are created - used Django include method on post-preview.html and post-snippet.html to have consistency between all website pages. Preview card renders the image, title, author, excerpt and engagement.
