### ISSUE TITLE
USER STORY: Add Favourite

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#23]
As a User, I can add articles to my favourites so that I can save my most enjoyed articles for future reference.

**Acceptance Criteria:**

1. Authenticated Users can click the "Like" button on the article detail page to add or remove the article from their favourites.
2. A visual distinction is provided to enable users to identify articles they have already marked as favourites
3. Users favourites are persisted to the database

**Tasks**
- [x] Add a clickable "Like" button to the article detail page for authenticated users. 
- [x] Implement a form that allows users to toggle the article ID in their favourites list.
- [x] Render a visual UI difference to indicate articles that the user has previously liked.
- [x] Notify users based on the outcome of the action

**Comment by DarrachBarneveld** [comment]
PostLike view class created to handle like form submissions. UI renders a different like button colour if the post is liked or unliked. Only authenticated users can like and unlike posts. Crud notifications added on operation outcome
