### ISSUE TITLE
USER STORY: Administration Approvals

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#27]
As the **Site Owner**, I can approve user created content so that I can manually oversee and manage content creation and edits.

**Acceptance Criteria:**
1. Admins can view all new/edited user created posts/comments
2. Admins must approve such posts before they are rendered to the site
3. Admins can delete unapproved content

**Tasks**
- [x] Updated content is rendered to the admin portal
- [x] Create admin functionality for quick and easy approval of content
- [x] Create functionality within the admin interface for deleting unapproved posts and comments.
- [x] Ensure that unapproved content is permanently deleted from the database

**Comment by DarrachBarneveld** [comment]
Admin users can approve all content before it is rendered to the website. Admins can perform all CRUD operations through the admin portal
