### ISSUE TITLE
USER STORY: Initial Heroku Deployment

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#3]
As a developer, I can perform an early deployment of the application to verify the functionality of the initial setup so that I can continue testing the application as it evolves during development.
 

**Tasks**
- [x] Create new app on Heroku  
- [x] Add all secret keys to config vars in the client setup
- [x] Create requirements.txt file with all packages required 
- [x] Create Procfile for Heroku gunicorn.wsgi
- [x] Deploy to Heroku and debug errors if required.

**Comment by DarrachBarneveld** [comment]
Deployed application on Heroku website, set to continually deploy throughout development
