### ISSUE TITLE
USER STORY: Administration Users

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#30]
As the **Site Owner**, I can view users and their profiles/content through the website's admin interface, allowing me to manage site users.

**Acceptance Criteria:**
1. Admins users possess the capability edit active users information
2. Admins can delete users and all associated content from the database
3. Admins can view all content posted by the users

**Tasks**
- [x] Modify the user model to include the profile and display it in the admin panel
- [x] Display all posts by a user in the admin panel
- [x] Implement the full spectrum of Create, Read, Update, and Delete functionalities within the admin interface.
- [x] Optimise data filtering and display mechanisms within the admin portal for enhanced usability.

**Comment by DarrachBarneveld** [comment]
Created a UserAdmin panel showcasing all relevant user information and content attributions with full CRUD functionality
