### ISSUE TITLE
USER STORY: User Level

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#36]
As a **User**, I can level up based on the number of posts I have contributed, so that I can be recognised for my active participation and contributions to the community.

**Acceptance Criteria:**
1.  A user starts at the initial level (e.g., Level 1) with no posts.
2. A user level increased based on the number of posts they have
3. Each level increase is reflected in the user's profile, providing a visual indication of their progress and level.

**Tasks**
- [x] Implement a system for tracking the number of posts a user has contributed. 
- [x] Add the user level to the user profile model 
- [x] Update the user's profile to display their current level image based on their post count 
- [x] Design and implement visual indicators (e.g., badges or icons) for each user level to provide recognition.

**Comment by DarrachBarneveld** [comment]
User level is rendered to the profile template and post detail page. Comments are also rendered with the user level trophy colour. Users level up based on the total number of posts they contribute. Profile model class calculates users score with a get_level function.
