### ISSUE TITLE
USER STORY: Account Deletion

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#39]
As a **User**, I can delete my account so that I can remove myself, details and all content from the live website

**Acceptance Criteria:**
1. Authenticated users can initiate the account deletion process
2. The account deletion process involves a confirmation step.
3. After confirming, the user's account and all associated content are permanently deleted.
4. Users receive a confirmation message upon successful account deletion or related errors

**Tasks**
- [x] Implement an account deletion button in the user settings.
- [x] Create a modal for account deletion confirmation.
- [x] Remove the user's account and associated content upon account deletion.
- [x] Render messages to the user upon successful/unsuccessful account deletion.

**Comment by DarrachBarneveld** [comment]
Users can now delete accounts from the update profile page. The delete account button has a confirmation modal before deletion. Users are notified with CRUD notifications up the result of their action
