### ISSUE TITLE
USER STORY: Wireframes

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#4]
As a developer I can layout wireframes so that I have a clear idea of the sites structure and theme

Identify the number of pages needed
 Create wireframes for mobile and desktop using Balsamiq

**Tasks**
- [x] Plan the total number of pages required
- [x] Create wireframes for mobile and desktop using Balsamiq editor
- [x] Save images into a documentation/wireframe images folder

**Comment by DarrachBarneveld** [comment]
All wireframes have been created using Balsamiq and uploaded to documentation
