### ISSUE TITLE
USER STORY: Custom Error Pages

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#40]
As a **developer**, I can show custom error pages redirect the user to the home page, so that I have a consistent experience even when encountering errors on the website.

**Acceptance Criteria:**
1. When an error occurs, I am presented with a custom error page that matches the website's theme.
2. The error page includes clear and user-friendly error messages to help me understand the issue.
3. The custom error page provides a link or button to navigate back to the home page of the website.
4. 

**Tasks**
- [x] Implement custom error pages for 404, 403, 404, 500
- [x] Design and integrate the custom error page templates to match the website's theme.
- [x] Include error messages in the custom error pages to provide informative feedback to users.
- [x] Add a navigation link or button on the error pages to allow users to return to the home page.

**Comment by DarrachBarneveld** [comment]
All main custom error pages have been created with redirect buttons to the websites home page. Each page has a description of the type of error for good UX.
