### ISSUE TITLE
USER STORY: Social Links

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#43]
As a **User**, I can click on the footer contact social links so I can find out more information about the brand

**Acceptance Criteria:**
1. The contact social links are prominently displayed on the websites footer.
2. Clicking on a social link takes me to the respective social media profiles or contact information of the brand.
3. The social links are correctly linked to the brand's official social media pages or contact channels.
4. The social links are visually distinguishable and labeled clearly.

**Tasks**
- [x]  Ensure that the contact social links are visible on the websites footer  
- [x]  Social Links are uniform in appearance besides brand logos
- [x]  Implement functionality to open the brand's official social media profiles or contact channels when the links are clicked.
- [x] Design a clean UI for focus/hover interactions

**Comment by DarrachBarneveld** [comment]
Footer is created with brand links and a clean UI. Focus and hover elements display the brands colour for further distinction between then websites. Links open in a separate tab
