### ISSUE TITLE
USER STORY: Pending Posts

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#45]
As a **User**, I can view my posts that are pending approval on my profile page so that I can track the status of my submitted content.

**Acceptance Criteria:**
1. When I visit my profile page, I see a section labeled "Pending Approval" that displays a list of my posts that are awaiting approval by moderators.
2. Each post in the "Pending Approval" should have a clear UI difference and not be inter actable 
3. Pending posts are only visible to the author of the post
4. 

**Tasks**
- [x] Create a "Pending Approval" section on the user's profile page.
- [x] Implement a mechanism to fetch and display the list of posts that are pending approval.
- [x] Design the layout and style of the "Pending Approval" card
- [x] Ensure only the post author can view the pending posts

**Comment by DarrachBarneveld** [comment]
Pending posts filtered and rendered to profile page. Pending post html include template rendered and only visible to author. Edit functionality included pre approval.
