### ISSUE TITLE
USER STORY: No Posts/Favourites

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#46]
As a **User**, I want to see a user-friendly interface when I have no posts or favourites on my profile page. Additionally, I want to have an option to easily add new content.

**Acceptance Criteria:**
1. When I visit my profile page and have no posts or favourites, I see a clear and informative message indicating that I don't have any posts or favourites yet.
2. Clicking the "Add Post" button should navigate me to the add post page
3. Clicking the "Add Favourites" button should navigate me to the home directory. 
4. I only see these interactive button elements if I am the profile owner

**Tasks**
- [x] Design and implement the user interface for the scenario when the user has no posts or favourites.
- [x] Implement the "Add Post" button on the profile page which routes to the Add post page
- [x] Implement the "Add Favourites" button on the profile page which routes to the home page
- [x] Ensure the buttons are only visible to the profile owner and not author visitors

**Comment by DarrachBarneveld** [comment]
No posts/favourites UI rendered with navigation buttons to home directory or add post page. Only visible to authenticated profile user.
