### ISSUE TITLE
USER STORY: Colour Theme

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#5]
As a developer I can choose a colour theme so that all pages have a consistent feel and style.

**Tasks**
- [x] A colour theme should be decided
- [x] The theme should meet minimum WebAIM Contrast Checker
- [x] All themed colours are set as css root variables
- [x] Theming image is saved in the documentation folder

**Comment by DarrachBarneveld** [comment]
Colour theme selected and meets appropriate guidelines
