### ISSUE TITLE
USER STORY: Messaging System

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#50]
As a **User**, I can use either a messaging system, so that I can efficiently interact with other users or contact the developer for assistance, enhancing my overall experience on the website.

**Acceptance Criteria:**

1. 1. There is a clear option on the website interface for either accessing the messaging system to communicate with other users or the ticket system to contact the developer for support.
2. I can use a form to contact users/developers via email 
3. Notifications are in place to inform me about new messages
4. Messages are secured and private.

**Tasks**

- [ ]  Design and implement the option for users to access either the messaging system or the ticket system.
- [ ]  Create the messaging system with a user interface form for sending messages.
- [ ]  Develop a notification system to inform users on new messages in the inbox
- [ ]  Ensure the privacy and security of messages in both systems
