### ISSUE TITLE
USER STORY: Code Of Conduct

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#53]
As a **Website Owner**, I can have a  "Code of Conduct" page with a list of conduct rules, so that users understand and adhere to the community guidelines.

**Acceptance Criteria:**

1. When I access the "Code of Conduct" page, I see a clear heading with the title "Code of Conduct."
2. The page displays a list of conduct rules in a visually appealing format with checkmark icons and descriptive text.
3. The rules are presented in an easy-to-read and organised manner.
4. I can navigate to the "Code of Conduct" page by clicking a link in the website's footer.

**Tasks**

- [x]  Create an HTML template for the "Code of Conduct" page.
- [x]  Create a Code of Conduct View and link it to a url and template
- [x]  Populate the template with a list of conduct rules.
- [x]  Ensure the "Code of Conduct" page is accessible from the website's footer by creating a link in the footer HTML.
- [x]  Ensure the list of conduct rules is easy to read and organised.

**Comment by DarrachBarneveld** [comment]
Code of conduct template created. List of community guidelines explained. View and urls linked up. Validation done
