### ISSUE TITLE
User Story: Responsive Layout

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#6]
As a user I want the website to be responsive so I can view it on multiple devices

**Tasks**
- [x] Determine the crucial components and areas of the website that require enhancement to ensure mobile responsiveness.
- [x] Design page layouts with a mobile first development approach
- [x] Use a combination of bootstrap, media queries and css modifications to ensure responsive behaviour

**Comment by DarrachBarneveld** [comment]
All pages rendered are responsive. The use of Bootstraps grid layout and rows is done to achieve the desired responsive page layout. Pages are designed with a mobile first development approach to ensure the easiest development experience.
