### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#7]
As a User I can intuitively navigate through the website so that I can view all content with ease.

**Tasks**
- [x] Create the navigation bar layout
- [x] Ensure all links in the navigation bar redirect to the correct page.
- [x] Ensure the navigation bar is fully responsive

**Comment by DarrachBarneveld** [comment]
Basic site navigation set up to content pages and authentication routes. Navbar is mobile responsive
