### ISSUE TITLE
USER STORY: Sign up

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#8]
As a **User**, I can create an account so that I can post, save and edit content

**Acceptance Criteria:**
1. User sign-up process should be easy to follow and intuitive.
2. The sign-up page should have clear error handling and validation for user input.
3. User registration data must be securely stored and processed.

**Tasks**
- [x] Create a register now button on the navbar
- [x]  Create a user registration form and render it to a template
- [x]  Implement error handling and user feedback
- [x]  Style the form in accordance with the current theming 
- [x]  Ensure a user profile is created that is linked to the auth user
- [x] Notify user on a successful registration

**Comment by DarrachBarneveld** [comment]
Users can register an account with error feedback and are notified of a successful registration
