### ISSUE TITLE
USER STORY: Log in

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/CoolCoders-PP4#9]
As a **User**, I can access my account so that I can create and edit content and view my saved information

**Acceptance Criteria:**
1. Users can successfully log in with valid, registered credentials.
2. Clear error handling and user feedback are provided for login failures.

**Tasks**
- [x] Create a login button on the navbar
- [x] Create a login form and render it as a template
- [x] Implement error-handling rendering to the UI.
- [x] Redirect users to the home page on a successful login
- [x] Notify user on a successful login

**Comment by DarrachBarneveld** [comment]
Users can confirm log in and are notified of the result
